import { OTypeDef } from "@common/definition";

export const loadMetrics = async (otype) => {
    const metrics = (otype === OTypeDef.SYSTEM)? instanceMetrics : businessMetrics;

    return Promise.resolve({data: metrics});
};

export const loadTarget = async (otype, domainId, searchTime) => {
    const targetList = (otype === OTypeDef.SYSTEM)? instanceList : businessList;

    return Promise.resolve({data: targetList});
};

const instanceMetrics = [["gc_time","403"],["gc_count","404"],["gc_time_usage","407"],["file_count","414"],["finalize_pending","408"],["heap_committed","426"],["heap_used","406"],["heap_usage","427"],["nonheap_used","409"],["sys_cpu","402"],["sys_mem","422"],["sys_mem_rate","423"],["proc_cpu","401"],["proc_mem","424"],["thread_daemon","410"],["thread_current","411"],["thread_started","412"],["collection_count","413"],["socket_count","415"],["service_count","301"],["service_time","302"],["service_err_count","303"],["service_slow_count","304"],["service_method_time","310"],["service_sql_time","305"],["service_externalcall_time","306"],["service_fetch_time","307"],["service_rate","308"],["service_cpu","309"],["active_service","201"],["bad_response_active_service","204"],["active_user","104"],["user_req_interval","106"],["concurrent_user","107"],["visit_hour","108"],["visit_day","109"],["event_normal_count","111"],["event_warning_count","112"],["event_fatal_count","113"],["event_count","115"],["error_count","114"],["sql_count","321"],["sql_time","322"],["externalcall_count","331"],["externalcall_time","332"],["fetch_count","341"],["fetch_time","342"],["frontend_measure_count","357"],["average_frontend_time","356"],["average_frontend_network_time","355"],["alive_agent","121"],["average_db_pool_active_count","428"],["average_db_pool_idle_count","429"],["average_db_pool_configured_count","430"],["max_db_pool_active_count","431"],["max_tps","317"],["max_active_service","205"],["max_sys_cpu","433"],["max_proc_cpu","432"],["max_sys_mem_rate","434"]];
const businessMetrics = [["user_req_interval","106"],["concurrent_user","107"],["sql_count","321"],["sql_time","322"],["externalcall_count","331"],["externalcall_time","332"],["fetch_count","341"],["fetch_time","342"],["service_count","301"],["service_time","302"],["service_err_count","303"],["service_slow_count","304"],["service_method_time","310"],["service_sql_time","305"],["service_externalcall_time","306"],["service_fetch_time","307"],["service_rate","308"],["service_cpu","309"],["active_service","201"],["bad_response_active_service","204"],["event_normal_count","111"],["event_warning_count","112"],["event_fatal_count","113"],["event_count","115"],["error_count","114"],["frontend_measure_count","357"],["average_frontend_time","356"],["average_frontend_network_time","355"],["max_tps","317"]];

const instanceList = [{"parent":null,"oid":75544,"oidObj":{"oid":75544},"shortName":"Release Build","longName":"10008","status":3,"licenseStatus":0,"selected":false,"ip":null,"languageType":0,"order":1,"connectedVersion":null,"instId":10008},{"parent":null,"oid":75545,"oidObj":{"oid":75545},"shortName":"file","longName":"파일공유 시스템 (php-fpm)","status":3,"licenseStatus":0,"selected":false,"ip":null,"languageType":0,"order":2,"connectedVersion":null,"instId":10009},{"parent":null,"oid":75538,"oidObj":{"oid":75538},"shortName":"rnd-web","longName":"192.168.0.10 apache","status":3,"licenseStatus":0,"selected":false,"ip":null,"languageType":0,"order":3,"connectedVersion":null,"instId":10002},{"parent":null,"oid":75537,"oidObj":{"oid":75537},"shortName":"Homepage","longName":"jennifersoft.com (apache2)","status":3,"licenseStatus":0,"selected":false,"ip":null,"languageType":0,"order":4,"connectedVersion":null,"instId":10001},{"parent":null,"oid":73313,"oidObj":{"oid":73313},"shortName":"JIRA","longName":"느림.","status":3,"licenseStatus":0,"selected":false,"ip":null,"languageType":0,"order":6,"connectedVersion":null,"instId":7777},{"parent":null,"oid":72638,"oidObj":{"oid":72638},"shortName":"Nexus","longName":"Nexus for Jennifer Build (8081 port of support)","status":3,"licenseStatus":0,"selected":false,"ip":null,"languageType":0,"order":7,"connectedVersion":null,"instId":7102}];
const businessList = {"list":[{"badResponseTimeLimit":"30000","ruleList":"/browse/*","bizId":"36","existData":true,"treeIndex":"0","oid":36,"shortName":"Jira","longName":""}]};